Repository Ludo-SMP/ludo-backend, pull requests merged in 2024-02, with the labels that each got.

#20 Sp 214 Hotfix: Cors 오류 / 카카오 소셜 오류 수정 / 스터디 생성 방식 변경 / 스터디 상태 변경에 따른 모집공고 상태 변화 적용
  src/main/java/com/ludo/study/studymatchingplatform/auth/kakao/service/KakaoSignUpService.java
  src/main/java/com/ludo/study/studymatchingplatform/auth/kakao/service/dto/KakaoUserProfileDto.java
  src/main/java/com/ludo/study/studymatchingplatform/config/WebConfig.java
  src/main/java/com/ludo/study/studymatchingplatform/filter/CorsFilter.java
  src/main/java/com/ludo/study/studymatchingplatform/filter/JwtAuthenticationFilter.java
  src/main/java/com/ludo/study/studymatchingplatform/study/controller/RecruitmentController.java
  src/main/java/com/ludo/study/studymatchingplatform/study/controller/StudyController.java
  src/main/java/com/ludo/study/studymatchingplatform/study/domain/Study.java
  src/main/java/com/ludo/study/studymatchingplatform/study/domain/recruitment/Recruitment.java
  src/main/java/com/ludo/study/studymatchingplatform/study/repository/StudyRepositoryImpl.java
  src/main/java/com/ludo/study/studymatchingplatform/study/service/RecruitmentService.java
  src/main/java/com/ludo/study/studymatchingplatform/study/service/StudyCreateService.java
  src/main/java/com/ludo/study/studymatchingplatform/study/service/StudyStatusService.java
  src/main/java/com/ludo/study/studymatchingplatform/study/service/dto/ParticipantRequest.java
  src/main/java/com/ludo/study/studymatchingplatform/study/service/dto/response/DeleteRecruitmentResponse.java
  src/main/resources/data.sql
Labels: 버그, 백엔드, 리팩토링

#23 SP-351/Feat: 로그아웃 및 토큰 인증 실패 시 쿠키 제거 로직 추가
  src/main/java/com/ludo/study/studymatchingplatform/auth/common/AuthController.java
  src/main/java/com/ludo/study/studymatchingplatform/auth/common/Redirection.java
  src/main/java/com/ludo/study/studymatchingplatform/auth/common/provider/CookieProvider.java
  src/main/java/com/ludo/study/studymatchingplatform/common/properties/ClientProperties.java
  src/main/java/com/ludo/study/studymatchingplatform/filter/JwtAuthenticationFilter.java
  src/main/resources/application.yaml
Labels: 백엔드

#24 SP-349/Feat: 회원 탈퇴 기능 추가
  src/main/java/com/ludo/study/studymatchingplatform/common/entity/BaseEntity.java
  src/main/java/com/ludo/study/studymatchingplatform/user/controller/UserController.java
  src/main/java/com/ludo/study/studymatchingplatform/user/service/UserService.java
Labels: 백엔드

#25 SP-352/Feat: 로그인 된 사용자 정보 제공 API
  src/main/java/com/ludo/study/studymatchingplatform/config/ServletFilterConfig.java
  src/main/java/com/ludo/study/studymatchingplatform/user/controller/UserController.java
  src/main/java/com/ludo/study/studymatchingplatform/user/service/dto/Me.java
Labels: 백엔드

#26 SP-356/Feat: 스터디 탈퇴 기능 추가
  src/main/java/com/ludo/study/studymatchingplatform/study/controller/StudyController.java
  src/main/java/com/ludo/study/studymatchingplatform/study/domain/Participant.java
  src/main/java/com/ludo/study/studymatchingplatform/study/domain/Study.java
  src/main/java/com/ludo/study/studymatchingplatform/study/service/StudyService.java
Labels: 백엔드

#27 SP-323/Feat: 스터디 상세 정보 조회
  src/main/java/com/ludo/study/studymatchingplatform/study/controller/StudyController.java
  src/main/java/com/ludo/study/studymatchingplatform/study/domain/Participant.java
  src/main/java/com/ludo/study/studymatchingplatform/study/domain/Study.java
  src/main/java/com/ludo/study/studymatchingplatform/study/repository/StudyRepositoryImpl.java
  src/main/java/com/ludo/study/studymatchingplatform/study/service/StudyFetchService.java
  src/main/java/com/ludo/study/studymatchingplatform/study/service/dto/request/EditRecruitmentRequest.java
  src/main/java/com/ludo/study/studymatchingplatform/study/service/dto/request/WriteRecruitmentRequest.java
  src/main/java/com/ludo/study/studymatchingplatform/study/service/dto/response/StudyDetailsResponse.java
  src/main/java/com/ludo/study/studymatchingplatform/study/service/dto/response/StudyParticipantResponse.java
Labels: 백엔드

#28 SP-348/Feat: 마이 페이지 API 구현
  src/main/java/com/ludo/study/studymatchingplatform/config/ServletFilterConfig.java
  src/main/java/com/ludo/study/studymatchingplatform/study/domain/Participant.java
  src/main/java/com/ludo/study/studymatchingplatform/study/domain/Study.java
  src/main/java/com/ludo/study/studymatchingplatform/study/domain/id/ParticipantId.java
  src/main/java/com/ludo/study/studymatchingplatform/study/domain/recruitment/Applicant.java
  src/main/java/com/ludo/study/studymatchingplatform/study/domain/recruitment/id/ApplicantId.java
  src/main/java/com/ludo/study/studymatchingplatform/study/repository/ParticipantRepositoryImpl.java
  src/main/java/com/ludo/study/studymatchingplatform/study/repository/PositionRepositoryImpl.java
  src/main/java/com/ludo/study/studymatchingplatform/study/repository/recruitment/ApplicantRepositoryImpl.java
  src/main/java/com/ludo/study/studymatchingplatform/study/service/ParticipantService.java
  src/main/java/com/ludo/study/studymatchingplatform/study/service/StudyCreateService.java
  src/main/java/com/ludo/study/studymatchingplatform/study/service/StudyStatusService.java
  src/main/java/com/ludo/study/studymatchingplatform/study/service/dto/request/WriteStudyRequest.java
  src/main/java/com/ludo/study/studymatchingplatform/study/service/dto/response/ParticipantResponse.java
  src/main/java/com/ludo/study/studymatchingplatform/user/controller/MyPageController.java
  src/main/java/com/ludo/study/studymatchingplatform/user/service/MyPageService.java
  src/main/java/com/ludo/study/studymatchingplatform/user/service/dto/response/ApplicantRecruitmentResponse.java
  src/main/java/com/ludo/study/studymatchingplatform/user/service/dto/response/CompletedStudyResponse.java
  src/main/java/com/ludo/study/studymatchingplatform/user/service/dto/response/MyPageResponse.java
  src/main/java/com/ludo/study/studymatchingplatform/user/service/dto/response/ParticipateStudyResponse.java
  src/test/java/com/ludo/study/studymatchingplatform/study/fixture/ApplicantFixture.java
  src/test/java/com/ludo/study/studymatchingplatform/study/fixture/ParticipantFixture.java
  src/test/java/com/ludo/study/studymatchingplatform/user/service/MyPageServiceTest.java
Labels: 백엔드, 테스트

#29 Sp 213/Refactor: 스터디 생성시 항목 추가
  .idea/modules/com.ludo.study.study-matching-platform.main.iml
  src/main/java/com/ludo/study/studymatchingplatform/study/domain/Platform.java
  src/main/java/com/ludo/study/studymatchingplatform/study/domain/Study.java
  src/main/java/com/ludo/study/studymatchingplatform/study/service/StudyCreateService.java
  src/main/java/com/ludo/study/studymatchingplatform/study/service/dto/request/WriteStudyRequest.java
  src/main/java/com/ludo/study/studymatchingplatform/study/service/dto/response/WriteStudyResponse.java
  src/test/java/com/ludo/study/studymatchingplatform/study/service/CreateStudyServiceTest.java
Labels: 백엔드, 리팩토링, 테스트

#30 SP-324/Feat: 지원자 수락, 거절 기능 구현
  src/main/java/com/ludo/study/studymatchingplatform/config/DataInitializer.java
  src/main/java/com/ludo/study/studymatchingplatform/study/controller/RecruitmentController.java
  src/main/java/com/ludo/study/studymatchingplatform/study/controller/dto/BaseApiResponse.java
  src/main/java/com/ludo/study/studymatchingplatform/study/domain/Study.java
  src/main/java/com/ludo/study/studymatchingplatform/study/domain/recruitment/Applicant.java
  src/main/java/com/ludo/study/studymatchingplatform/study/domain/recruitment/Recruitment.java
  src/main/java/com/ludo/study/studymatchingplatform/study/domain/recruitment/id/ApplicantId.java
  src/main/java/com/ludo/study/studymatchingplatform/study/repository/ParticipantRepositoryImpl.java
  src/main/java/com/ludo/study/studymatchingplatform/study/repository/recruitment/ApplicantRepositoryImpl.java
  src/main/java/com/ludo/study/studymatchingplatform/study/service/StudyApplicantDecisionService.java
  src/main/java/com/ludo/study/studymatchingplatform/study/service/dto/request/StudyApplicantDecisionRequest.java
  src/test/java/com/ludo/study/studymatchingplatform/study/domain/StudyTest.java
  src/test/java/com/ludo/study/studymatchingplatform/study/fixture/ApplicantFixture.java
  src/test/java/com/ludo/study/studymatchingplatform/study/fixture/CategoryFixture.java
  src/test/java/com/ludo/study/studymatchingplatform/study/fixture/StudyFixture.java
  src/test/java/com/ludo/study/studymatchingplatform/study/service/StudyApplicantDecisionServiceTest.java
Labels: 백엔드, 테스트

#31 Sp-218/Feat: 인기있는 모집 공고 목록 조회
  src/main/java/com/ludo/study/studymatchingplatform/study/controller/RecruitmentController.java
  src/main/java/com/ludo/study/studymatchingplatform/study/controller/dto/response/BaseApiResponse.java
  src/main/java/com/ludo/study/studymatchingplatform/study/repository/recruitment/RecruitmentRepositoryImpl.java
  src/main/java/com/ludo/study/studymatchingplatform/study/service/PopularRecruitmentsFindService.java
  src/main/java/com/ludo/study/studymatchingplatform/study/service/dto/mapper/RecruitmentPreviewResponseMapper.java
  src/main/java/com/ludo/study/studymatchingplatform/study/service/dto/response/PopularRecruitmentsResponse.java
  src/main/java/com/ludo/study/studymatchingplatform/study/service/dto/response/RecruitmentPreviewResponse.java
  src/main/resources/application.yaml
  src/test/java/com/ludo/study/studymatchingplatform/study/service/PopularRecruitmentsFindServiceTest.java
Labels: 백엔드, 테스트
